enableGlobalVirtualStore: true
autoInstallPeers: false

peerDependencyRules:
  ignoreMissing:
    - preact
    - svelte
    - vue

allowBuilds:
  '@vscode/vsce-sign': false
  esbuild: false
  keytar: false

minimumReleaseAgeExclude:
  - '@embedpdf/core-acrojs@3.0.0-next.10'
  - '@embedpdf/core-annotation@3.0.0-next.10'
  - '@embedpdf/core-geometry@3.0.0-next.10'
  - '@embedpdf/core-js-sandbox@3.0.0-next.10'
  - '@embedpdf/core-stage@3.0.0-next.10'
  - '@embedpdf/core-ui@3.0.0-next.10'
  - '@embedpdf/core@3.0.0-next.10'
  - '@embedpdf/engine-core@3.0.0-next.10'
  - '@embedpdf/engine-runtime-darwin-arm64@3.0.0-next.10'
  - '@embedpdf/engine-runtime-darwin-x64@3.0.0-next.10'
  - '@embedpdf/engine-runtime-linux-arm64@3.0.0-next.10'
  - '@embedpdf/engine-runtime-linux-x64@3.0.0-next.10'
  - '@embedpdf/engine-runtime-linuxmusl-arm64@3.0.0-next.10'
  - '@embedpdf/engine-runtime-linuxmusl-x64@3.0.0-next.10'
  - '@embedpdf/engine-runtime-wasm32@3.0.0-next.10'
  - '@embedpdf/engine-runtime-win32-arm64@3.0.0-next.10'
  - '@embedpdf/engine-runtime-win32-x64@3.0.0-next.10'
  - '@embedpdf/engine-runtime@3.0.0-next.10'
  - '@embedpdf/engine-services@3.0.0-next.10'
  - '@embedpdf/engine@3.0.0-next.10'
  - '@embedpdf/plugin-annotation@3.0.0-next.10'
  - '@embedpdf/plugin-commands@3.0.0-next.10'
  - '@embedpdf/plugin-form@3.0.0-next.10'
  - '@embedpdf/plugin-i18n@3.0.0-next.10'
  - '@embedpdf/plugin-interaction@3.0.0-next.10'
  - '@embedpdf/plugin-link@3.0.0-next.10'
  - '@embedpdf/plugin-metadata@3.0.0-next.10'
  - '@embedpdf/plugin-page-edit@3.0.0-next.10'
  - '@embedpdf/plugin-redaction@3.0.0-next.10'
  - '@embedpdf/plugin-render@3.0.0-next.10'
  - '@embedpdf/plugin-search@3.0.0-next.10'
  - '@embedpdf/plugin-selection@3.0.0-next.10'
  - '@embedpdf/plugin-shell@3.0.0-next.10'
  - '@embedpdf/plugin-stage@3.0.0-next.10'
  - '@embedpdf/plugin-stamp@3.0.0-next.10'
  - '@embedpdf/plugin-view-manager@3.0.0-next.10'
  - '@embedpdf/react@3.0.0-next.10'
  - '@embedpdf/web@3.0.0-next.10'
