enableGlobalVirtualStore: true
autoInstallPeers: false

peerDependencyRules:
  ignoreMissing:
    - preact
    - svelte
    - vue

allowBuilds:
  '@vscode/vsce-sign': false
  esbuild: false
  keytar: false
